### ISSUE TITLE
Feature Request: Add discussion topic

### ISSUE THREAD

**Issue by nstielau** [bgilbert/11bot#2]
It would be nice to be able to set a discussion topic, which would show up in the 1:1 introduction ping from the bot.  So instead of 

> Hi @AAAA and @BBB!  You've been grouped for a 1:1 this week.  Use this group chat to discuss timing and details.

It could be

> Hi @AAAA and @BBB!  You've been grouped for a 1:1 this week.  Use this group chat to discuss timing and details.
>
> The discussion topic for this week is:
>
> Will the world end, the sun burning out, before we ship feature XYZ?

This could be set in the channel via something like

> /11bot topic Will the world end, the sun burning out, before we ship feature XYZ?

**Comment by bgilbert** [comment]
The bot is intended for casual social interactions, not for meetings, so I'm disinclined to add this.  You could always post discussion prompts directly in the associated Slack channel.
